### ISSUE TITLE
IRC? Hilfsmoeglichkeiten... Ist IRC wirklich noch sooo hipop, dass wir das in der  Praesentation von LPD auffuehren?

### ISSUE THREAD

**Issue by TheRojam** [netz39/Talks#11]

**Comment by LeSpocky** [comment]
Wird angepasst, aber es ist tatsächlich so, dass im Kernel-Umfeld und im Embedded Bereich da noch sehr viel IRC am Start ist.

**Comment by LeSpocky** [comment]
Xubuntu verweist bspw. auch sehr prominent auf IRC: https://xubuntu.org/help/
